### ISSUE TITLE
Emacs slowing down/freezes when opening files on slow smb-share

### ISSUE THREAD

**Issue by technician77** [bbatsov/projectile#1008] opened 2016-05-04 00:08 UTC
**Expected behavior:**
File opens as fast as possible, editing shows no difference in speed between local file and remote file

**Actual behavior:**
Emacs takes a lot longer to open the file. Moving around the cursor takes for every move around 20 seconds to be show. All other emacs operations like closing the file again are delayed a lot.

**Steps to reproduce the problem:**
Open file on remote smb share. A small text-file only 1KB. The smb-share has to be very slowly connected let's say connected via 0,5Mbit not more.

**Environment & Version information:**
(projectile-global-mode)
(setq projectile-indexing-method 'alien)

**Projectile version information:**
20160420.1508

**Emacs version:**
25.0.93.1 (x86_64-w64-mingw32)

**Operating system:**
Windows 7 64bit

**Comment by floli** [comment] 2016-09-13 13:10
See #657, this is probably the same problem. The issue is closed, but it does not seem to be resolved.

**Comment by bbatsov** [comment] 2016-12-29 07:06
This should be fixed by some recent project name caching improvements.

**Closed by bbatsov** 2016-12-29 07:06 UTC
