### ISSUE TITLE
Wrong type argument: stringp, nil

### ISSUE THREAD

**Issue by kulbida** [bbatsov/projectile#920] opened 2015-12-02 21:43 UTC
While trying to find other file getting with `M-x helm-projectile-find-other-file` getting this:
Wrong type argument: stringp, nil

Debugger output:

```
1 Debugger entered--Lisp error: (wrong-type-argument stringp nil)
2   file-name-nondirectory(nil)
3   projectile-associated-file-name-extensions(nil)
4   projectile-get-other-files(nil (".gitattributes" ".gitignore" "Capfile" "DEPLOY_NOTES.md" "DEVELOPMENT_TARGET_VERSION.rb" "Gemfile" "Gemfile.lock" "Procfile" "README.md" "Rakefile" "app$
5   helm-projectile-find-other file(nil)
6   call-interactively(helm-projectile-find-other-file nil nil)
7   command-execute(helm-projectile-find-other-file) 
```

**Comment by bbatsov** [comment] 2016-10-06 05:31
Seems like a duplicate of https://github.com/bbatsov/helm-projectile/issues/10

**Closed by bbatsov** 2016-10-06 05:31 UTC
