### ISSUE TITLE
projectile-replace sometimes fails with a weird error.

### ISSUE THREAD

**Issue by rgrinberg** [bbatsov/projectile#1219] opened 2018-02-16 09:20 UTC
Running `projectile-replace` sometimes fails with an opaque error

## Expected behavior

Replace expected strings in my buffer.

## Actual behavior

```
Debugger entered--Lisp error: (args-out-of-range #<buffer run.t<multiple-private-libs>> 0 0)
  buffer-substring-no-properties(0 0)
  perform-replace("private-doc" "doc-private" t nil nil nil (keymap (78 . exit-current) (89 . automatic-all) keymap (escape . exit-prefix) (M-prior . scroll-other-window-down) (M-next . scroll-other-window) (prior . scroll-down) (next . scroll-up) (27 keymap (33554454 . scroll-other-window-down) (22 . scroll-other-window) (118 . scroll-down)) (22 . scroll-up) (29 . quit) (7 . quit) (63 . help) (help . help) (f1 . help) (8 . help) (85 . undo-all) (117 . undo) (94 . backup) (33 . automatic) (12 . recenter) (23 . delete-and-edit) (18 . edit) (46 . act-and-exit) (return . exit) (13 . exit) (113 . exit) (44 . act-and-show) (69 . edit-replacement) (101 . edit-replacement) (78 . skip) (89 . act) (110 . skip) (121 . act) (backspace . skip) (delete . skip) (127 . skip) (32 . act)))
  eval((perform-replace '"private-doc" '"doc-private" t nil nil nil multi-query-replace-map))
  tags-loop-eval((perform-replace '"private-doc" '"doc-private" t nil nil nil multi-query-replace-map))
  tags-loop-continue((list "/Users/rgrinberg/reps/dune/test/blackbox-tests/test-cases/multiple-private-libs/run.t" "/Users/rgrinberg/reps/dune/src/build_system.ml" "/Users/rgrinberg/reps/dune/src/odoc.ml"))
  projectile-replace(nil)
  funcall-interactively(projectile-replace nil)
  call-interactively(projectile-replace nil nil)
  command-execute(projectile-replace)
```

## Steps to reproduce the problem

Unfortunately, I'm unable to give exact steps to reproduce. My buffer simply get into a state where this error keeps occuring.

### Projectile version information

Projectile 20180128.655

### Emacs version

GNU Emacs 26.0.90 (build 1, x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911))
 of 2017-10-12

**Comment by bbatsov** [comment] 2018-09-20 06:39
I didn't manage to reproduce this myself and it seems no one else has, so I'll just close this ticket.

**Closed by bbatsov** 2018-09-20 06:39 UTC

**Comment by camsaul** [comment] 2019-10-18 18:49
I've been running into this pretty consistently over the past few months

**Comment by camsaul** [comment] 2019-10-18 18:49
Currently on 20190626.1315

**Comment by camsaul** [comment] 2019-10-18 19:04
It might be something weird with `helm-M-x`, because when I `(call-interactively #'projectile-replace)` I don't see the error

**Comment by camsaul** [comment] 2019-10-18 21:32
It sounds like this is actually an upstream issue in Emacs itself: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=31586

This GitHub issue describes the same problem as well: https://github.com/syl20bnr/spacemacs/issues/9700
